directories:
  root: "."
  raw_data: "data/raw"
  processed_data: "data/processed"
  final_data: "data/final"
  model_store: "models"
  logs: "logs"

files:
  # Updated to match your screenshot exactly
  train: "train_v2.csv"
  members: "members_v3.csv"
  transactions: "transactions_v2.csv"
  user_logs: "user_logs_v2.csv"
  
  final_output: "master_features.parquet"